version: "3.8"

services:
  server:
    build: ./Server
    container_name: aistudio_server
    ports:
      - "5000:5000"
    env_file:
      - ./Server/.env
    restart: always
    networks:
      - aistudio_net

  client:
    build: ./Client
    container_name: aistudio_client
    ports:
      - "80:80"
    restart: always
    networks:
      - aistudio_net

networks:
  aistudio_net:
